<Project>
	<PropertyGroup>
		<!-- Enable central package management -->
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Allure.Reqnroll" Version="2.12.1" />
		<PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
		<PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
	</ItemGroup>
</Project>