[project]
name = "python test package manager"
version = "1.0.0"
description = "validate that Renovate creates PRs for python/pipy"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "requests==2.33.0",      # HTTP library for making API calls to Bitbucket
    "schedule==1.2.0"       # Job scheduling library for delayed testing
]
